# Generated by Django 2.2.7 on 2019-11-22 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MadLadParser', '0002_auto_20191122_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='story_array',
            field=models.CharField(blank=True, default=None, max_length=1500),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_name',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_text',
            field=models.CharField(blank=True, default=None, max_length=1500),
        ),
    ]
